language: go

go:
  - 1.x

env:
  - GO111MODULE=on

install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/mattn/goveralls

script:
  - golangci-lint run ./...
  - go test -v -cover -coverprofile=./coverage.out ./...

after_script:
  - goveralls -coverprofile=./coverage.out -service=travis-ci
