name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Get Sources
        uses: actions/checkout@v1

      - name: Get Tools
        run: |
          GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          GO111MODULE=off go get -u github.com/ricallinson/covfmt

      - name: Lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run ./...

      - name: Run Tests
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go test -v -cover -coverprofile=./coverage.out ./...
          cat ./coverage.out | covfmt > ./coverage.lcov

      - name: Publish Coverage
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage.lcov
          github-token: ${{ secrets.github_token }}
